// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyeoxaihpdlxfqyysfle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5ZW94YWlocGRseGZxeXlzZmxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MTM2NDgsImV4cCI6MjA2NDI4OTY0OH0.x0lnisaCSOmfjpBPHIQb7TfRA9Z6b-4q-QvmjTIUJGQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);